# Generated by Django 4.2.13 on 2024-07-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTable',
            fields=[
                ('certificateid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('product_name', models.CharField(max_length=15, verbose_name='产品名称')),
                ('product_size', models.CharField(max_length=110, verbose_name='产品规格')),
                ('material', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='材质')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('heat_number', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='炉号')),
                ('certificate_number', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='证书编号')),
                ('certificate_date', models.DateField(max_length=10, verbose_name='证书日期')),
                ('certificate_file', models.CharField(max_length=110, verbose_name='证书文件')),
                ('cover_file', models.CharField(max_length=110, verbose_name='封面文件')),
            ],
            options={
                'db_table': 'certificate_tb',
            },
        ),
        migrations.CreateModel(
            name='CheckContentsTable',
            fields=[
                ('checkid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('in_process_inspection', models.SmallIntegerField(choices=[(1, '首次检验'), (2, '巡查检验'), (3, '终次检验')], verbose_name='检验次数')),
                ('inspection_number', models.CharField(max_length=50, unique=True, verbose_name='检验单号')),
                ('inspection_quantity', models.IntegerField(verbose_name='检验数量')),
                ('inspector_name', models.CharField(max_length=10, verbose_name='检验员姓名')),
                ('reference_image', models.FileField(upload_to='images/reference_image/', verbose_name='参考图片')),
                ('inspection_adress', models.CharField(max_length=10, verbose_name='检验地点')),
                ('inspection_date', models.DateField(verbose_name='检验时间')),
                ('inspection_standard', models.CharField(max_length=20, verbose_name='检验标准')),
                ('inspection_type', models.SmallIntegerField(choices=[(1, '来料检验'), (2, '开料检验'), (3, '组装检验'), (4, '焊接检验'), (5, '锌层检验'), (6, '涂层检验')], verbose_name='检验类型')),
            ],
            options={
                'db_table': 'check_contents_tb',
            },
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('customer_name', models.CharField(max_length=150, unique=True, verbose_name='客户名称')),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='客户地址')),
                ('contact_username', models.CharField(blank=True, max_length=20, null=True, verbose_name='联络人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=80, null=True, verbose_name='联络人电话')),
                ('fax_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='传真号码')),
                ('district', models.CharField(max_length=10, verbose_name='地区')),
                ('remarks', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
        migrations.CreateModel(
            name='DriverTable',
            fields=[
                ('driverid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('driver_name', models.CharField(max_length=10, unique=True, verbose_name='司机姓名')),
                ('driver_phone', models.CharField(max_length=30, verbose_name='司机电话')),
                ('licence_plate', models.CharField(max_length=10, unique=True, verbose_name='车牌')),
            ],
            options={
                'db_table': 'driver_tb',
            },
        ),
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('inventoryid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_size', models.CharField(max_length=100, verbose_name='产品规格')),
                ('unit', models.SmallIntegerField(choices=[(1, '件'), (2, '套'), (3, '批'), (4, '千克'), (5, '吨'), (6, '包'), (7, '盒'), (8, '其他')], verbose_name='单位')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='品牌')),
                ('material_certificate', models.CharField(blank=True, max_length=10, null=True, verbose_name='材质')),
                ('material_type', models.SmallIntegerField(choices=[(1, '原材料'), (2, '焊材'), (3, '耗材'), (4, '工具'), (5, '配件'), (6, '螺丝'), (7, '钻铣')], verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'inventory_tb',
            },
        ),
        migrations.CreateModel(
            name='KVTable',
            fields=[
                ('key', models.CharField(help_text='key', max_length=254, primary_key=True, serialize=False)),
                ('value', models.TextField(help_text='value', null=True)),
            ],
            options={
                'db_table': 'kv_tb',
            },
        ),
        migrations.CreateModel(
            name='ManagedTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='名称', max_length=50, null=True)),
                ('nickname', models.CharField(help_text='昵称', max_length=50, null=True)),
                ('email', models.CharField(help_text='邮箱', max_length=50, null=True, unique=True)),
                ('age', models.IntegerField(default=0, help_text='年龄', null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='分数', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'managed_tb',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailTable',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('commodity_details', models.CharField(max_length=10, verbose_name='品名')),
                ('commodity_size', models.CharField(max_length=100, verbose_name='规格')),
                ('control_no', models.CharField(max_length=10, verbose_name='编号')),
                ('commodity_units', models.CharField(max_length=5, verbose_name='单位')),
                ('commodity_quantity', models.IntegerField(verbose_name='产品数量')),
                ('commodity_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='重量')),
                ('in_warehouse_quantity', models.IntegerField(default=0, null=True, verbose_name='库存数量')),
                ('remarks', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'order_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('shipping_address', models.CharField(max_length=200, unique=True, verbose_name='送货地点')),
                ('project_contact_name', models.CharField(max_length=20, verbose_name='联络人姓名')),
                ('project_contact_phone', models.CharField(max_length=80, verbose_name='联络人电话')),
            ],
            options={
                'db_table': 'project_tb',
            },
        ),
        migrations.CreateModel(
            name='SupplierTable',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('supplier_name', models.CharField(max_length=110, unique=True, verbose_name='供应商名')),
                ('supplier_contact_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='联络人姓名')),
                ('supplier_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='联络人电话')),
                ('supplier_address', models.CharField(blank=True, max_length=110, null=True, verbose_name='地址')),
                ('service_content', models.CharField(max_length=50, verbose_name='服务内容')),
                ('approval_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'db_table': 'supplier_tb',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('role', models.SmallIntegerField(choices=[(1, '管理员'), (2, '跟单员'), (3, '质检员'), (4, '仓管员')], verbose_name='角色')),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTable',
            fields=[
                ('warehouseid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('product_name', models.CharField(max_length=15, verbose_name='产品名称')),
                ('product_size', models.CharField(max_length=110, verbose_name='产品规格')),
                ('unit', models.SmallIntegerField(choices=[(1, '件'), (2, '套'), (3, '批'), (4, '千克'), (5, '吨'), (6, '包'), (7, '盒'), (8, '其他')], verbose_name='单位')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='数量')),
                ('brand', models.CharField(blank=True, max_length=25, null=True, verbose_name='品牌')),
                ('material_certificate', models.CharField(blank=True, max_length=30, null=True, verbose_name='材质')),
                ('material_type', models.SmallIntegerField(choices=[(1, '原材料'), (2, '焊材'), (3, '耗材'), (4, '工具'), (5, '配件'), (6, '螺丝'), (7, '钻铣')], verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'warehouse_tb',
            },
        ),
        migrations.CreateModel(
            name='WarehousEntryTable',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('entry_number', models.CharField(max_length=30, unique=True, verbose_name='入库单号')),
                ('filename', models.CharField(max_length=100, verbose_name='入库单')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suppliertable', to_field='supplier_name', verbose_name='供应商')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='经办人')),
            ],
            options={
                'db_table': 'warehouse_entry_tb',
            },
        ),
        migrations.AddField(
            model_name='suppliertable',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='经办人'),
        ),
        migrations.CreateModel(
            name='ShippingTable',
            fields=[
                ('shippingid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('delivery_date', models.DateField(max_length=10, verbose_name='出货日期')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.customertable', to_field='customer_name', verbose_name='客户名')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.drivertable', to_field='driver_name', verbose_name='司机姓名')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.projecttable', verbose_name='项目名称')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='发货人')),
            ],
            options={
                'db_table': 'shipping_tb',
            },
        ),
        migrations.CreateModel(
            name='ShippingDetailTable',
            fields=[
                ('shippingdetailid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('shipping_quantity', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='发货数量')),
                ('detailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderdetailtable', verbose_name='产品编号')),
                ('shippingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shippingtable', verbose_name='送货单号')),
            ],
            options={
                'db_table': 'shipping_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='RequestBuyTable',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_size', models.CharField(max_length=100, verbose_name='产品规格')),
                ('material', models.CharField(blank=True, max_length=10, null=True, verbose_name='材质')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=5, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('requestdate', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('whether_buy', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否采购')),
                ('remarks', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='申请人')),
            ],
            options={
                'db_table': 'request_buy_tb',
            },
        ),
        migrations.CreateModel(
            name='PurchaseTable',
            fields=[
                ('purchaseid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('purchase_number', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('contact_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('purchase_date', models.DateField(max_length=10, verbose_name='采购日期')),
                ('currency', models.CharField(max_length=5, verbose_name='币种')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suppliertable', to_field='supplier_name', verbose_name='供应商名称')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='采购员')),
            ],
            options={
                'db_table': 'purchase_tb',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetailTable',
            fields=[
                ('purchasedetailid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_size', models.CharField(max_length=100, verbose_name='产品规格')),
                ('material', models.CharField(blank=True, max_length=10, null=True, verbose_name='材质')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=5, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('purchase_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchasetable', to_field='purchase_number', verbose_name='采购单号')),
            ],
            options={
                'db_table': 'purchase_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='ProductionProcessTable',
            fields=[
                ('processid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('process_name', models.CharField(max_length=50, verbose_name='工艺名称')),
                ('process_quantity', models.IntegerField(default=0, null=True, verbose_name='当前完成数量')),
                ('detailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderdetailtable', verbose_name='产品号码')),
            ],
            options={
                'db_table': 'production_process_tb',
            },
        ),
        migrations.CreateModel(
            name='OutwardProcessing',
            fields=[
                ('outwardid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('outward_number', models.CharField(max_length=20, unique=True, verbose_name='外发清单编号')),
                ('outwardprocess_date', models.DateField(max_length=10, verbose_name='日期')),
                ('remarks', models.CharField(max_length=30, null=True, verbose_name='备注')),
                ('outward_processing_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.suppliertable', verbose_name='供应商id')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='申请人')),
            ],
            options={
                'db_table': 'outward_process_tb',
            },
        ),
        migrations.CreateModel(
            name='OutwardDetail',
            fields=[
                ('outwarddetailid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('commodity_qty', models.IntegerField(verbose_name='数量')),
                ('currency', models.CharField(max_length=5, verbose_name='币种')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('outward_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.outwardprocessing', to_field='outward_number', verbose_name='外发清单编号')),
            ],
            options={
                'db_table': 'outward_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='OutgoingWarehouseTable',
            fields=[
                ('outid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('outdate', models.DateField(verbose_name='出库日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('person_name', models.CharField(max_length=10, verbose_name='领料人')),
                ('inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventorytable', verbose_name='库存ID')),
            ],
            options={
                'db_table': 'outgoing_warehouse_tb',
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='订单号码')),
                ('order_date', models.DateField(max_length=10, verbose_name='订单日期')),
                ('delivery_date', models.DateField(max_length=10, verbose_name='预出货日期')),
                ('invoice_date', models.DateField(max_length=10, verbose_name='对账日期')),
                ('order_status', models.SmallIntegerField(choices=[(1, '生产中'), (2, '已完成')], default=1, verbose_name='订单状态')),
                ('order_details', models.CharField(max_length=50, verbose_name='订单内容')),
                ('remarks', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.customertable', to_field='customer_name', verbose_name='客户名称')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.projecttable', verbose_name='项目名称')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usertable', to_field='username', verbose_name='跟单员')),
            ],
            options={
                'db_table': 'order_tb',
            },
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码'),
        ),
        migrations.CreateModel(
            name='InvoicesTable',
            fields=[
                ('invoicesid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('invoices_number', models.CharField(max_length=50, unique=True, verbose_name='发票号码')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('batch', models.CharField(blank=True, max_length=10, null=True, verbose_name='批次')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customertable', to_field='customer_name', verbose_name='客户名称')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码')),
                ('shippingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shippingtable', verbose_name='货单编号')),
            ],
            options={
                'db_table': 'invoices_tb',
            },
        ),
        migrations.CreateModel(
            name='InvoicesDetailTable',
            fields=[
                ('invoicesdetailid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('detail', models.CharField(max_length=100, verbose_name='内容')),
                ('unit', models.CharField(max_length=5, verbose_name='单位')),
                ('currency', models.CharField(max_length=5, verbose_name='币种')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('invoices_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoicestable', to_field='invoices_number', verbose_name='发票号码')),
            ],
            options={
                'db_table': 'invoices_detail_tb',
            },
        ),
        migrations.CreateModel(
            name='IncomingWarehouseTable',
            fields=[
                ('incomeid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='单价')),
                ('total_prices', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总价')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('entry_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehousentrytable', to_field='entry_number', verbose_name='入库单号')),
                ('inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventorytable', verbose_name='库存ID')),
            ],
            options={
                'db_table': 'incoming_warehouse_tb',
            },
        ),
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('filename', models.CharField(max_length=50, verbose_name='文件名')),
                ('new_filename', models.CharField(max_length=50, verbose_name='新文件名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.IntegerField(verbose_name='文件大小')),
                ('file_suffix', models.CharField(max_length=20, verbose_name='文件后缀')),
                ('file_type', models.SmallIntegerField(choices=[(1, '合同/订单'), (2, '图纸'), (3, '已签收发货单'), (4, '验焊报告'), (5, '质检报告'), (6, '镀锌报告'), (7, '其他')], verbose_name='文件类型')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码')),
            ],
            options={
                'db_table': 'file_tb',
            },
        ),
        migrations.CreateModel(
            name='CuttingQualityTable',
            fields=[
                ('cutid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('material', models.CharField(max_length=50, verbose_name='材料')),
                ('inspection_point', models.CharField(max_length=3, verbose_name='检测点')),
                ('required_value', models.CharField(max_length=10, verbose_name='要求值')),
                ('tolerance', models.CharField(max_length=5, verbose_name='公差')),
                ('actual_dimension', models.CharField(max_length=10, verbose_name='实际尺寸')),
                ('judgment', models.SmallIntegerField(choices=[(1, '合格'), (2, '不合格')], verbose_name='判断')),
                ('cutting_edge', models.BooleanField(verbose_name='切割口')),
                ('flatness', models.BooleanField(verbose_name='平直度')),
                ('other', models.CharField(blank=True, max_length=35, null=True, verbose_name='其他')),
                ('other_result', models.CharField(blank=True, max_length=35, null=True, verbose_name='其他结果')),
                ('image1', models.FileField(blank=True, null=True, upload_to='images/size_image', verbose_name='图片1')),
                ('image2', models.FileField(blank=True, null=True, upload_to='images/size_image', verbose_name='图片2')),
                ('image3', models.FileField(blank=True, null=True, upload_to='images/size_image', verbose_name='图片3')),
                ('inspection_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.checkcontentstable', to_field='inspection_number', verbose_name='检验单号')),
            ],
            options={
                'db_table': 'cutting_quality_tb',
            },
        ),
        migrations.AddField(
            model_name='checkcontentstable',
            name='detailid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderdetailtable', verbose_name='构件ID'),
        ),
        migrations.AddField(
            model_name='checkcontentstable',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码'),
        ),
        migrations.AddConstraint(
            model_name='productionprocesstable',
            constraint=models.UniqueConstraint(fields=('detailid', 'process_name'), name='unique_detailid_process_name'),
        ),
    ]
