# Generated by Django 4.2.13 on 2024-07-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_projecttable_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytable',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
