# Generated by Django 4.2.13 on 2024-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inventorytable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousetable',
            name='material_certificate',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='材质'),
        ),
    ]
