# Generated by Django 4.2.13 on 2024-07-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_warehousetable_material_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytable',
            name='material_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='inventorytable',
            name='remark',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备注'),
        ),
    ]
