# Generated by Django 4.2.13 on 2024-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventorytable_material_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousentrytable',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入库单'),
        ),
    ]
