# Generated by Django 4.2.13 on 2024-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_warehousentrytable_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='invoice_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='对账日期'),
        ),
    ]
