# Generated by Django 4.2.13 on 2024-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_project_name_ordertable_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='projectid',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='project_name',
            field=models.CharField(default=1, max_length=50, verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
