# Generated by Django 4.2.13 on 2024-07-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_ordertable_projectid_ordertable_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='in_warehouse_quantity',
        ),
    ]
