# Generated by Django 4.2.13 on 2024-07-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orderdetailtable_in_warehouse_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtable',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
    ]
