# Generated by Django 4.2.13 on 2024-07-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_shippingtable_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailtable',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.customertable', to_field='customer_name', verbose_name='客户名称'),
        ),
    ]
