# Generated by Django 4.2.13 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderdetailtable_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='commodity_details',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='commodity_quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='commodity_size',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='commodity_units',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='commodity_weight',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='control_no',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='订单号码'),
        ),
    ]
