# Generated by Django 4.2.13 on 2024-07-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_orderdetailtable_commodity_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailtable',
            name='commodity_details',
            field=models.CharField(default=1, max_length=10, verbose_name='品名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='commodity_quantity',
            field=models.IntegerField(default=1, verbose_name='产品数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='commodity_size',
            field=models.CharField(default=1, max_length=100, verbose_name='规格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='commodity_units',
            field=models.CharField(default=1, max_length=5, verbose_name='单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='commodity_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='重量'),
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='control_no',
            field=models.CharField(default=1, max_length=10, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.customertable', to_field='customer_name', verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='order_number',
            field=models.CharField(default=1, max_length=50, verbose_name='订单号码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailtable',
            name='remarks',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备注'),
        ),
    ]
