# Generated by Django 4.2.13 on 2024-07-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderdetailtable_commodity_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='detailid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
