# Generated by Django 4.2.13 on 2024-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_orderdetailtable_detailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailtable',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='单件重量'),
        ),
    ]
