# Generated by Django 4.2.13 on 2024-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_orderdetailtable_unit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetailtable',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='出货重量'),
        ),
    ]
