# Generated by Django 4.2.13 on 2024-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_productionprocesstable_processid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailtable',
            name='username',
            field=models.CharField(default=1, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
