# Generated by Django 4.2.13 on 2024-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_orderdetailtable_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='manufacture_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='计划生产日期'),
        ),
    ]
