# Generated by Django 4.2.13 on 2024-07-29 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_ordertable_manufacture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='manufacture_date',
            field=models.DateField(default=datetime.date.today, max_length=10, verbose_name='计划生产日期'),
        ),
    ]
