# Generated by Django 4.2.13 on 2024-07-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_orderdetailtable_control_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='commodity_details',
            field=models.CharField(max_length=25, verbose_name='品名'),
        ),
    ]
