# Generated by Django 4.2.13 on 2024-07-31 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_orderdetailtable_commodity_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetable',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.customertable', to_field='customer_name', verbose_name='客户名称'),
        ),
    ]
