# Generated by Django 4.2.13 on 2024-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_inventorytable_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousentrytable',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='录入时间'),
        ),
    ]
