# Generated by Django 4.2.13 on 2024-08-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_warehousentrytable_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtable',
            name='project_name',
        ),
        migrations.AddField(
            model_name='shippingtable',
            name='shipping_address',
            field=models.CharField(default=1, max_length=50, verbose_name='送货地址'),
            preserve_default=False,
        ),
    ]
