# Generated by Django 4.2.13 on 2024-08-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_shippingtable_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='order_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码'),
        ),
    ]
