# Generated by Django 4.2.13 on 2024-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_orderdetailtable_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetable',
            name='upload_time',
            field=models.DateField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='requestbuytable',
            name='requestdate',
            field=models.DateField(auto_now_add=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='suppliertable',
            name='approval_date',
            field=models.DateField(auto_now_add=True, verbose_name='录入时间'),
        ),
    ]
