# Generated by Django 4.2.13 on 2024-08-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_filetable_upload_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailtable',
            name='requestid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.requestbuytable', verbose_name='待采表ID'),
            preserve_default=False,
        ),
    ]
