# Generated by Django 4.2.13 on 2024-08-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_purchasedetailtable_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='shpping_status',
            field=models.SmallIntegerField(choices=[(1, '未出货'), (2, '已出货')], default=1, verbose_name='出货状态'),
        ),
    ]
