# Generated by Django 4.2.13 on 2024-08-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ordertable_shpping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprocesstable',
            name='order_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码'),
        ),
    ]
