# Generated by Django 4.2.13 on 2024-08-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_productionprocesstable_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='order_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码'),
            preserve_default=False,
        ),
    ]
