# Generated by Django 4.2.13 on 2024-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_orderdetailtable_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '生产中'), (2, '已完成'), (0, '已暂停')], default=1, verbose_name='订单状态'),
        ),
    ]
