# Generated by Django 4.2.13 on 2024-08-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_ordertable_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetable',
            name='AOG_status',
            field=models.SmallIntegerField(choices=[(1, '未到货'), (2, '已到货')], default=1, verbose_name='到货状态'),
        ),
    ]
