# Generated by Django 4.2.13 on 2024-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_purchasetable_aog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='shpping_status',
        ),
        migrations.RemoveField(
            model_name='productionprocesstable',
            name='order_number',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='shpping_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='出货日期'),
        ),
    ]
