# Generated by Django 4.2.13 on 2024-08-17 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_ordertable_shpping_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='shpping_date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), max_length=10, null=True, verbose_name='出货日期'),
        ),
    ]
