# Generated by Django 4.2.13 on 2024-08-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_outwarddetail_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetailtable',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='purchasedetailtable',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='purchasetable',
            name='contact_number',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='purchasetable',
            name='contact_person',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='联系人'),
        ),
    ]
