# Generated by Django 4.2.13 on 2024-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_outwarddetail_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwarehousetable',
            name='total_prices',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='incomingwarehousetable',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='单价'),
        ),
    ]
