# Generated by Django 4.2.13 on 2024-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_incomingwarehousetable_total_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='control_no',
            field=models.CharField(max_length=50, verbose_name='编号'),
        ),
    ]
