# Generated by Django 4.2.13 on 2024-11-09 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_orderdetailtable_control_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='quote_date',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), max_length=10, null=True, verbose_name='报价日期'),
        ),
    ]
