# Generated by Django 4.2.13 on 2025-03-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ordertable_quote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_tolerance', models.CharField(blank=True, max_length=10, null=True, verbose_name='通用公差')),
                ('inspection_quantity', models.PositiveIntegerField(verbose_name='检验数量')),
                ('inspection_location', models.CharField(max_length=100, verbose_name='检验地点')),
                ('inspection_standard', models.CharField(max_length=255, verbose_name='检验标准')),
                ('inspection_number', models.CharField(max_length=50, unique=True, verbose_name='检验单号')),
                ('material', models.CharField(max_length=255, verbose_name='材料')),
                ('cutting_quantity', models.PositiveIntegerField(verbose_name='切割数量')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reference_image', models.FileField(upload_to='images/reference_image/', verbose_name='参考图片')),
                ('inspector_name', models.CharField(max_length=10, verbose_name='检验员')),
                ('deformation_status', models.BooleanField(default=False, verbose_name='变形')),
                ('cutting_perpendicularity', models.BooleanField(default=False, verbose_name='切口垂直度')),
                ('slag_residue', models.BooleanField(default=False, verbose_name='是否有熔渣残留')),
                ('cutting_roughness', models.BooleanField(default=False, verbose_name='切口粗糙度')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码')),
            ],
        ),
    ]
