# Generated by Django 4.2.13 on 2025-03-20 01:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_inspectioncuttingdetailrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_1',
            field=models.ImageField(blank=True, null=True, storage=app.models.OverwriteStorage(), upload_to='images/reference_image/', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=app.models.OverwriteStorage(), upload_to='images/reference_image/', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_3',
            field=models.ImageField(blank=True, null=True, storage=app.models.OverwriteStorage(), upload_to='images/reference_image/', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='inspection_number',
            field=models.CharField(max_length=50, verbose_name='检验单号'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingrecord',
            name='reference_image',
            field=models.FileField(storage=app.models.OverwriteStorage(), upload_to='images/reference_image/', verbose_name='参考图片'),
        ),
    ]
