# Generated by Django 4.2.13 on 2025-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_inspectioncuttingdetailrecord_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncuttingdetailrecord',
            name='inspection_number_id',
            field=models.CharField(default=1, max_length=50, verbose_name='检验单号'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CuttingQualityTable',
        ),
    ]
