# Generated by Django 4.2.13 on 2025-03-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_inspectioncuttingdetailrecord_inspection_number_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectioncuttingdetailrecord',
            name='inspection_number_id',
        ),
    ]
