# Generated by Django 4.2.13 on 2025-03-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_inspectioncuttingdetailrecord_inspection_number_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectioncuttingdetailrecord',
            name='inspection_number',
        ),
    ]
