# Generated by Django 4.2.13 on 2025-03-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_inspectioncuttingdetailrecord_inspection_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncuttingdetailrecord',
            name='inspection_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.inspectioncuttingrecord', to_field='inspection_number', verbose_name='检验单号'),
            preserve_default=False,
        ),
    ]
