# Generated by Django 4.2.13 on 2025-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_inspectioncuttingdetailrecord_inspection_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncuttingrecord',
            name='general_tolerance',
            field=models.CharField(default=1, max_length=255, verbose_name='通用公差'),
            preserve_default=False,
        ),
    ]
