# Generated by Django 4.2.13 on 2025-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_inspectioncuttingrecord_general_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingdetailrecord',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='inspectioncuttingrecord',
            name='reference_image',
            field=models.FileField(upload_to='images/reference_image/', verbose_name='参考图片'),
        ),
    ]
