# Generated by Django 4.2.13 on 2025-04-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_inspectionassemblyrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionWeldingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_quantity', models.PositiveIntegerField(verbose_name='检验数量')),
                ('inspection_location', models.CharField(max_length=100, verbose_name='检验地点')),
                ('inspection_standard', models.CharField(max_length=255, verbose_name='检验标准')),
                ('general_tolerance', models.CharField(max_length=255, verbose_name='通用公差')),
                ('inspection_number', models.CharField(max_length=50, unique=True, verbose_name='检验单号')),
                ('component_number', models.CharField(max_length=255, verbose_name='构件编号')),
                ('welding_quantity', models.PositiveIntegerField(verbose_name='构件数量')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='参考图片')),
                ('inspector_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='检验员')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customertable', to_field='customer_name', verbose_name='客户名称')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordertable', to_field='order_number', verbose_name='订单号码')),
            ],
            options={
                'verbose_name': '焊接检验记录表',
                'verbose_name_plural': '焊接检验记录表',
                'db_table': 'inspection_welding_record_tb',
            },
        ),
        migrations.CreateModel(
            name='InspectionWeldingDetailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.IntegerField(verbose_name='检查点')),
                ('required_value', models.FloatField(verbose_name='要求值')),
                ('tolerance', models.CharField(max_length=50, verbose_name='公差')),
                ('actual_value', models.FloatField(verbose_name='实际值')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/reference_image/', verbose_name='图片3')),
                ('pointX', models.FloatField(verbose_name='X 坐标')),
                ('pointY', models.FloatField(verbose_name='Y 坐标')),
                ('inspection_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inspectionweldingrecord', to_field='inspection_number', verbose_name='检验单号')),
            ],
            options={
                'verbose_name': '焊接检验详情表',
                'verbose_name_plural': '焊接检验详情表',
                'db_table': 'inspection_welding_record_detail_tb',
            },
        ),
    ]
