# Generated by Django 4.2.13 on 2025-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_inspectionweldingrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='crack',
            field=models.BooleanField(default=False, verbose_name='裂纹'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='depression',
            field=models.BooleanField(default=False, verbose_name='凹陷'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='porosity',
            field=models.BooleanField(default=False, verbose_name='气孔'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='slag',
            field=models.BooleanField(default=False, verbose_name='熔渣'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='spatter',
            field=models.BooleanField(default=False, verbose_name='飞溅'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='undercut',
            field=models.BooleanField(default=False, verbose_name='咬边'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='weldBead',
            field=models.BooleanField(default=False, verbose_name='焊瘤'),
        ),
    ]
