# Generated by Django 4.2.13 on 2025-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_inspectionweldingdetailrecord_crack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_corner_joint',
            field=models.BooleanField(default=False, verbose_name='角接接头'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_cruciform_joint',
            field=models.BooleanField(default=False, verbose_name='十字接头'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_in_line_butt_joint',
            field=models.BooleanField(default=False, verbose_name='对接接头(直通)'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_node_tky_joint',
            field=models.BooleanField(default=False, verbose_name='节点(TKY)接头'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_other_joint',
            field=models.BooleanField(default=False, verbose_name='其他'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='ck_tee_joint',
            field=models.BooleanField(default=False, verbose_name='T字接头'),
        ),
        migrations.AddField(
            model_name='inspectionweldingrecord',
            name='other_joint_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='其他接头说明'),
        ),
    ]
