# Generated by Django 4.2.13 on 2025-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_inspectionweldingrecord_ck_corner_joint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_corner_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_cruciform_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_in_line_butt_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_node_tky_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_other_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='ck_tee_joint',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingrecord',
            name='other_joint_text',
        ),
    ]
