# Generated by Django 4.2.13 on 2025-04-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_inspectionweldingrecord_ck_corner_joint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='crack',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='depression',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='porosity',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='spatter',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='undercut',
        ),
        migrations.RemoveField(
            model_name='inspectionweldingdetailrecord',
            name='weldBead',
        ),
    ]
