# Generated by Django 4.2.13 on 2025-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_inspectionweldingdetailrecord_crack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='visual_check',
            field=models.BooleanField(default=False, verbose_name='外观检查'),
        ),
        migrations.AddField(
            model_name='inspectionweldingdetailrecord',
            name='weld_process',
            field=models.CharField(default=1, max_length=20, verbose_name='焊接工艺'),
            preserve_default=False,
        ),
    ]
