# Generated by Django 4.2.13 on 2025-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_inspectionfinishrecord_inspectionfinishsurfacerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionfinishrecord',
            name='film_thickness',
            field=models.CharField(default=1, max_length=255, verbose_name='通用膜厚'),
            preserve_default=False,
        ),
    ]
