# Generated by Django 4.2.13 on 2025-04-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_inspectionfinishrecord_film_thickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='品名')),
                ('specifications', models.CharField(max_length=120, verbose_name='规格')),
                ('material', models.CharField(max_length=50, verbose_name='材质')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('quantity_unit', models.CharField(default='PC', max_length=10, verbose_name='数量单位')),
                ('heat_batch_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='炉号 / 批号')),
                ('certificate_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='材质证明书编号')),
                ('received_date', models.DateField(verbose_name='收货日期')),
                ('record_code', models.CharField(max_length=20, unique=True, verbose_name='记录编号')),
            ],
            options={
                'verbose_name': '材料清单',
                'verbose_name_plural': '材料清单',
                'db_table': 'material_list',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['record_code'], name='material_li_record__d41f1f_idx'), models.Index(fields=['certificate_number'], name='material_li_certifi_6e5c3c_idx')],
            },
        ),
    ]
