# Generated by Django 4.2.13 on 2025-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_materiallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallist',
            name='heat_batch_number',
            field=models.CharField(default=1, max_length=60, verbose_name='炉号 / 批号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
    ]
