# Generated by Django 4.2.13 on 2025-04-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_materiallist_heat_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallist',
            name='quantity_unit',
        ),
    ]
