# Generated by Django 4.2.13 on 2025-04-26 09:40

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_materiallist_quantity_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInspectionRecord',
            fields=[
                ('inspection_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='检验单号')),
                ('inspection_location', models.CharField(max_length=60, verbose_name='检验地点')),
                ('inspection_standard', models.CharField(max_length=120, verbose_name='检验标准')),
                ('inspector_name', models.CharField(max_length=10, verbose_name='检验员')),
                ('created_date', models.DateField(verbose_name='创建日期')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customertable', to_field='customer_name', verbose_name='客户名称')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ordertable', to_field='order_number', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '来料检验-表头',
                'verbose_name_plural': '来料检验-表头',
                'db_table': 'incoming_inspection_record',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomingInspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='品名')),
                ('spec', models.CharField(max_length=120, verbose_name='规格')),
                ('material', models.CharField(max_length=50, verbose_name='材质')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('length', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='长度(mm)')),
                ('width', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='宽度(mm)')),
                ('thickness', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='厚度(mm)')),
                ('height', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='高度(mm)')),
                ('heat_no', models.CharField(blank=True, max_length=60, null=True, verbose_name='炉号')),
                ('mtc_no', models.CharField(blank=True, max_length=60, null=True, verbose_name='材质证明书编号')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=app.models.incoming_image_path, verbose_name='图片1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=app.models.incoming_image_path, verbose_name='图片2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=app.models.incoming_image_path, verbose_name='图片3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=app.models.incoming_image_path, verbose_name='图片4')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.incominginspectionrecord', verbose_name='所属表头')),
            ],
            options={
                'verbose_name': '来料检验-明细',
                'verbose_name_plural': '来料检验-明细',
                'db_table': 'incoming_inspection_detail',
                'ordering': ['record', 'id'],
                'indexes': [models.Index(fields=['record'], name='incoming_in_record__57bcca_idx')],
            },
        ),
    ]
