# Generated by Django 4.2.13 on 2025-04-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_incominginspectiondetail_inspection_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incominginspectiondetail',
            name='inspection_number',
        ),
    ]
