# Generated by Django 4.2.13 on 2025-04-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_remove_incominginspectiondetail_inspection_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incominginspectiondetail',
            options={'verbose_name': '来料检验-明细', 'verbose_name_plural': '来料检验-明细'},
        ),
        migrations.RemoveIndex(
            model_name='incominginspectiondetail',
            name='incoming_in_record__57bcca_idx',
        ),
        migrations.RemoveField(
            model_name='incominginspectiondetail',
            name='record',
        ),
    ]
