# Generated by Django 4.2.13 on 2025-04-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_incominginspectiondetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginspectiondetail',
            name='inspection_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.incominginspectionrecord', verbose_name='检验单号'),
            preserve_default=False,
        ),
    ]
