# Generated by Django 4.2.13 on 2025-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_alter_purchasetable_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetailtable',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='requestbuytable',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量'),
        ),
    ]
