# Generated by Django 4.2.13 on 2025-05-29 09:13

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0075_alter_purchasedetailtable_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetable',
            name='filename',
            field=models.CharField(max_length=150, verbose_name='文件名'),
        ),
        migrations.CreateModel(
            name='AttachmentFileTable',
            fields=[
                ('attachmentid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('object_id', models.PositiveIntegerField(verbose_name='所属记录 PK')),
                ('file', models.FileField(upload_to=app.models.upload_to, verbose_name='文件')),
                ('filename', models.CharField(max_length=150, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('parent_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='父单号 (兼容)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype', verbose_name='所属模型')),
            ],
            options={
                'db_table': 'attachment_file_tb',
                'index_together': {('content_type', 'object_id')},
            },
        ),
    ]
