# Generated by Django 4.2.13 on 2025-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_filetable_filename_attachmentfiletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentfiletable',
            name='parent_order_number',
        ),
    ]
