# Generated by Django 4.2.13 on 2025-06-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_attachmentfiletable_parent_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingwarehousetable',
            name='total_prices',
        ),
        migrations.RemoveField(
            model_name='incomingwarehousetable',
            name='unit_price',
        ),
    ]
