# Generated by Django 4.2.13 on 2025-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_remove_incomingwarehousetable_total_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtable',
            name='sign_back',
            field=models.SmallIntegerField(choices=[(1, '否'), (2, '是')], default=1, verbose_name='是否上传回单'),
        ),
    ]
